/* 입양 시각 구하기(1) */
-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 20 -- 09:00부터 19:59까지
GROUP BY HOUR(DATETIME) -- 시간대 별
ORDER BY HOUR(DATETIME) -- 시간대 순으로 정렬